### ISSUE TITLE
Trying to pull matches?

### ISSUE THREAD

**Issue by smkly** [Coriou/py-tinder#2]
Hi I'm trying to pull the matches, but it pulls back an empty array, when I have matches. Not sure how to fix.

Thanks!

tinder.post_updates(lastActivity=None)['matches']

**Comment by Coriou** [comment]
Hello. To be honest, I haven't been back to it since I pushed it here. Maybe their API was updated (probably). I'll give it a look when I get some time.

**Comment by twon23** [comment]
Works fine for me. Also got messages working, it's very basic so I will do some more work on it.
